"""Initial schema

Revision ID: 286875803e33
Revises: 
Create Date: 2023-12-03 23:46:49.180234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286875803e33'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fastapi_sessions',
    sa.Column('session_key', sa.String(length=40), nullable=False),
    sa.Column('session_data', sa.Text(), nullable=True),
    sa.Column('exire_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_index(op.f('ix_fastapi_sessions_exire_date'), 'fastapi_sessions', ['exire_date'], unique=False)
    op.create_index(op.f('ix_fastapi_sessions_session_key'), 'fastapi_sessions', ['session_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_sessions_session_key'), table_name='fastapi_sessions')
    op.drop_index(op.f('ix_fastapi_sessions_exire_date'), table_name='fastapi_sessions')
    op.drop_table('fastapi_sessions')
    # ### end Alembic commands ###
