"""expire_date typo fix

Revision ID: 3de821723dcd
Revises: 286875803e33
Create Date: 2023-12-06 00:25:54.032832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de821723dcd'
down_revision: Union[str, None] = '286875803e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fastapi_sessions', sa.Column('expire_date', sa.DateTime(timezone=True), nullable=False))
    op.drop_index('ix_fastapi_sessions_exire_date', table_name='fastapi_sessions')
    op.create_index(op.f('ix_fastapi_sessions_expire_date'), 'fastapi_sessions', ['expire_date'], unique=False)
    op.drop_column('fastapi_sessions', 'exire_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fastapi_sessions', sa.Column('exire_date', sa.DATETIME(), nullable=False))
    op.drop_index(op.f('ix_fastapi_sessions_expire_date'), table_name='fastapi_sessions')
    op.create_index('ix_fastapi_sessions_exire_date', 'fastapi_sessions', ['exire_date'], unique=False)
    op.drop_column('fastapi_sessions', 'expire_date')
    # ### end Alembic commands ###
